apiVersion: v1
kind: Pod
metadata:
  name: tranql
  labels:
    service: tranql
    app: tranql
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: tranql-backplane
    image: greentranslator/tranql-base
    command: [ "/usr/local/bin/gunicorn", "--workers=2", "--bind=0.0.0.0:8099", "--name=backplane", "--timeout=600", "tranql.backplane.server:app" ]
    ports:
      - containerPort: 8099
        name: http
    env:
      - name: BACKPLANE_PORT
        value: "8099"
    resources:
      requests:
        memory: 200Mi
      limits:
        memory: 1Gi
  - name: tranql-app
    image: greentranslator/tranql-app
    command: [ "/usr/local/bin/gunicorn", "--workers=2", "--bind=0.0.0.0:8001", "--name=tranql", "--timeout=600", "tranql.api:app" ]
    ports:
      - containerPort: 8001
        name: http
    env:
      - name: APP_PORT
        value: "8001"
      - name: BACKPLANE
#        value: http://tranql-backplane:8099
        value: http://localhost:8099
    resources:
      requests:
        memory: 200Mi
      limits:
        memory: 1Gi
  restartPolicy: OnFailure
