version: "3.4"
services:

  # A Redis instance for celery task result storage.
  redis:
    image: redis
    ports:
      - "${RESULTS_PORT}:${RESULTS_PORT}"
    command: --port ${RESULTS_PORT}

  # An AMQP Queue for Celery
  amqp:
    image: rabbitmq:3
    environment:
      - ADMIN_PASSWORD
      - BROKER_PASSWORD
      - RABBITMQ_DEFAULT_VHOST
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    hostname: rabbit_node_1
    ports:      
      - "${BROKER_PORT}2:5672"
      - "${BROKER_ADMIN_PORT}:15672"
    hostname: amqp

  # The Rosetta distributed task queue.
  rosetta_task_queue:
    # image: greent/robokop-rank
    build:
      context: .
    env_file:
      - ./rosetta.env
    environment:
      - APP_HOME=/home/rosetta/reasoner-tools
      - RESULTS_HOST=results
      - BROKER_HOST=amqp
    ports:
      - "${APP_PORT}:${APP_PORT}"
#      - "${SUPERVISOR_PORT}:${SUPERVISOR_PORT}"
    links:
      - redis
      - amqp
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  # An OpenAPI Interface to the service.
  rosetta_api:
    build:
      context: api
    env_file:
      - ./rosetta.env
    environment:
      - APP_HOME
    links:
      - rosetta_task_queue
      
#networks:
#  default:
#    external:
#      name: ${COMPOSE_PROJECT_NAME}_default
