version: "3.4"
services:

  # A Redis instance for celery task storage.
  redis:
    image: redis
    ports:
      - "${RESULTS_PORT}:${RESULTS_PORT}"
    command: --port ${RESULTS_PORT}

  # An AMQP Queue for Celery
  amqp:
    image: rabbitmq:3
    environment:
      - ADMIN_PASSWORD
      - BROKER_PASSWORD
      - BROKER_USER
      - RABBITMQ_DEFAULT_VHOST
    ports:
      #- "5672:5672"
      - "${BROKER_PORT}:${BROKER_PORT}"
    hostname: amqp
