version: "3.4"
services:

  # A Redis instance for celery task storage.
  redis:
    image: redis
    ports:
      - "${RESULTS_PORT}:${RESULTS_PORT}"
    command: --port ${RESULTS_PORT}

  # An AMQP Queue for Celery
  amqp:
    image: rabbitmq:3
    environment:
      - ADMIN_PASSWORD
      - BROKER_PASSWORD
      - BROKER_USER
      - RABBITMQ_DEFAULT_VHOST
    ports:
      #- "5672:5672"
      - "${BROKER_PORT}:${BROKER_PORT}"
    hostname: amqp

  # The Rosetta service.
  rosetta:
    # image: greent/robokop-rank
    build:
      context: .
    env_file:
      - ./rosetta.env
    environment:
      - APP_HOME=/home/rosetta/reasoner-tools
      - RESULTS_HOST=results
      - BROKER_HOST=amqp
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${SUPERVISOR_PORT}:${SUPERVISOR_PORT}"
    links:
      - redis
      - amqp
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
        
#networks:
#  default:
#    external:
#      name: ${COMPOSE_PROJECT_NAME}_default
