apiVersion: v1
kind: Pod
metadata:
  name: bionames
  labels:
    service: bionames
    app: bionames
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: green-bionames
    image: renciorg/green-bionames
    ports:
    env:
      - name: APP_PORT
        value: "5001"
    resources:
      requests:
        memory: 200Mi
      limits:
        memory: 1Gi
  restartPolicy: OnFailure
