apiVersion: apps/v1
kind: Deployment
metadata:
  name: bionames-deployment
  namespace: translator
  labels:
    service: bionames
    app: bionames
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bionames
  template:
    metadata:
      labels:
        app: bionames
    spec:
      volumes:
        - name: nfs-volume
          nfs:
            # URL for the NFS server
            server: arrival.edc.renci.org
            path: /srv/k8s-pvs/translator/logs

      terminationGracePeriodSeconds: 10
      containers:
      - name: bionames
        image: renciorg/green-bionames:latest
        ports:
        env:
          - name: APP_PORT
            value: "5001"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ACCESS_LOG
            value: "/var/nfs/bionames_access_log"
          - name: ERROR_LOG
            value: "/var/nfs/bionames_error_log"
        volumeMounts:
          - name: nfs-volume
            mountPath: /var/nfs
            subPathExpr: $(POD_NAME)
        resources:
          requests:
            memory: 200Mi
          limits:
            memory: 1Gi
        stdin: true
      restartPolicy: Always
