export ROSETTA_WF_PORT=5005

export RESULTS_PORT=6379
export CELERY_APP_PACKAGE="greent.flow.dag"
export RABBITMQ_DEFAULT_VHOST=rosetta
export PYTHONPATH=$APP_ROOT
export APP_NAME=rosetta
export RABBITMQ_DEFAULT_VHOST=$APP_NAME

export BROKER_USER=guest
export BROKER_PASSWORD=guest
export ADMIN_PASSWORD=admin
export BROKER_AUTH="$BROKER_USER:$BROKER_PASSWORD@"

export BROKER_HOSTNAME=localhost
export BROKER_CONNECT_ID=rabbit

export CELERY_BROKER_URL="amqp://${BROKER_AUTH}$BROKER_HOST:$BROKER_PORT/${APP_NAME}"
export CELERY_RESULT_BACKEND="redis://$RESULTS_HOST:$RESULTS_PORT/$RANKER_RESULTS_DB"

export SUPERVISOR_PORT=9003
