# Rosetta Global.
export APP_NAME=rosetta
export PYTHONPATH=$APP_ROOT

# Rosetta API.
export ROSETTA_WF_PORT=5007

# AMQP server.
export RABBITMQ_DEFAULT_VHOST=$APP_NAME
export RABBITMQ_DEFAULT_USER=guest
export RABBITMQ_DEFAULT_PASS=guest
#export ADMIN_PASSWORD=admin
export BROKER_AUTH="$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@"
export BROKER_HOST=amqp
export BROKER_PORT=12333
export BROKER_ADMIN_PORT=12334

# Celery Task Queue - AMQP and Redis result store config.
export RESULTS_PORT=6345
export CELERY_BROKER_URL="amqp://$RABBITMQ_DEFAULT_USER:$RABBITMQ_DEFAULT_PASS@$BROKER_HOST:$BROKER_PORT/$RABBITMQ_DEFAULT_VHOST"
export CELERY_RESULT_BACKEND="redis://$RESULTS_HOST:$RESULTS_PORT/$RANKER_RESULTS_DB"
export CELERY_APP_PACKAGE="greent.flow.dag"

# Gamma config.
export GAMMA_HOST=${BUILDER_HOST:-localhost}
export BUILDER_PORT=6010
export RANKER_PORT=6011
export BUILDER_BUILD_GRAPH_ENDPOINT=api/
export BUILDER_TASK_STATUS_ENDPOINT=api/task/
export ROBOKOP_BUILDER_BUILD_GRAPH_URL="http://$GAMMA_HOST:$BUILDER_PORT/${BUILDER_BUILD_GRAPH_ENDPOINT}"
export ROBOKOP_BUILDER_TASK_STATUS_URL="http://$GAMMA_HOST:$BUILDER_PORT/${BUILDER_TASK_STATUS_ENDPOINT}"
export ROBOKOP_ANSWERS_NOW_ENDPOINT=api/now
export ROBOKOP_RANKER_ANSWERS_NOW_URL="http://$GAMMA_HOST:$RANKER_PORT/${ROBOKOP_ANSWERS_NOW_ENDPOINT}"

f() {
export SUPERVISOR_PORT=9004
}
